version: '3'

services:
  ci-build:
    image: microsoft/aspnetcore-build:1.0-1.1
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./Differences.WebApi.sln && dotnet publish ./Differences.WebApi.sln -c Release -o ./obj/Docker/publish"
    #command: /bin/bash -c "dotnet restore ./Differences.IdentityServer.sln && dotnet publish ./Differences.IdentityServer.sln -c Release -o ./obj/Docker/publish"